# Generated by Django 3.1.7 on 2021-03-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stoic', '0002_auto_20210309_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, verbose_name='Наименование месяца')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='stoic',
            options={'ordering': ['id'], 'verbose_name': 'Высказывание', 'verbose_name_plural': 'Дни'},
        ),
        migrations.AddField(
            model_name='stoic',
            name='month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='stoic.month', verbose_name='Месяц'),
        ),
    ]
