# Generated by Django 3.1.7 on 2021-03-10 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stoic', '0003_auto_20210310_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='month',
            options={'ordering': ['id'], 'verbose_name': 'Месяц', 'verbose_name_plural': 'Месяцы'},
        ),
        migrations.AlterField(
            model_name='stoic',
            name='month',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='stoic.month', verbose_name='Месяц'),
            preserve_default=False,
        ),
    ]
