# Generated by Django 3.1.7 on 2021-03-10 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stoic', '0004_auto_20210310_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoic',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
